export const dates = [
  {
    date: "2024-05-03",
    user: "Juan Perez",
    time: "10:00 AM",
    duration: "1 hora",
    reason: "Consulta médica de rutina",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-05-15",
    user: "María López",
    time: "3:30 PM",
    duration: "45 minutos",
    reason: "Seguimiento de tratamiento",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-06-07",
    user: "Carlos Ramírez",
    time: "11:15 AM",
    duration: "30 minutos",
    reason: "Examen de laboratorio",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-06-20",
    user: "Ana García",
    time: "9:45 AM",
    duration: "1 hora",
    reason: "Consulta de especialidad",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
  {
    date: "2024-07-05",
    user: "Luisa Martínez",
    time: "2:00 PM",
    duration: "1 hora",
    reason: "Consulta de seguimiento",
    state: "pending",
    doctor: "Dr. David Garcia",
    color: "orange",
  },
  {
    date: "2024-07-18",
    user: "Pedro Sánchez",
    time: "4:30 PM",
    duration: "45 minutos",
    reason: "Revisión de resultados",
    state: "canceled",
    doctor: "Dr. Doctor Prueba",
    color: "red",
  },
  {
    date: "2024-05-07",
    user: "Roberto Gómez",
    time: "8:00 AM",
    duration: "30 minutos",
    reason: "Consulta inicial",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-06-10",
    user: "Elena Diaz",
    time: "1:45 PM",
    duration: "1 hora",
    reason: "Consulta de control",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-06-25",
    user: "Sofía Castro",
    time: "10:30 AM",
    duration: "45 minutos",
    reason: "Revisión médica",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-07-12",
    user: "Mario Ortiz",
    time: "11:00 AM",
    duration: "30 minutos",
    reason: "Consulta de seguimiento",
    state: "canceled",
    doctor: "Dr. Doctor Prueba",
    color: "red",
  },
  {
    date: "2024-05-10",
    user: "Laura Gonzalez",
    time: "9:00 AM",
    duration: "30 minutos",
    reason: "Consulta de rutina",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-05-12",
    user: "Ricardo Flores",
    time: "11:00 AM",
    duration: "1 hora",
    reason: "Consulta por dolor de espalda",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-05-12",
    user: "Marta Blanco",
    time: "2:00 PM",
    duration: "45 minutos",
    reason: "Revisión de exámenes",
    state: "canceled",
    doctor: "Dr. David Garcia",
    color: "red",
  },
  {
    date: "2024-05-20",
    user: "Ignacio Ortega",
    time: "10:00 AM",
    duration: "1 hora",
    reason: "Consulta de especialidad",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
  {
    date: "2024-05-25",
    user: "Sara Luna",
    time: "3:00 PM",
    duration: "30 minutos",
    reason: "Consulta de control",
    state: "pending",
    doctor: "Dr. David Garcia",
    color: "orange",
  },
  {
    date: "2024-05-30",
    user: "Victor Moreno",
    time: "4:00 PM",
    duration: "45 minutos",
    reason: "Consulta por alergias",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
  {
    date: "2024-06-02",
    user: "Paula Perez",
    time: "9:30 AM",
    duration: "1 hora",
    reason: "Revisión general",
    state: "canceled",
    doctor: "Dr. David Garcia",
    color: "red",
  },
  {
    date: "2024-06-05",
    user: "Fernando Ruiz",
    time: "11:00 AM",
    duration: "30 minutos",
    reason: "Consulta de seguimiento",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-06-10",
    user: "Julia Torres",
    time: "1:00 PM",
    duration: "45 minutos",
    reason: "Examen de rutina",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-06-15",
    user: "Hector Diaz",
    time: "10:30 AM",
    duration: "1 hora",
    reason: "Consulta de especialidad",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
  {
    date: "2024-06-20",
    user: "Isabel Fernandez",
    time: "3:00 PM",
    duration: "30 minutos",
    reason: "Consulta por hipertensión",
    state: "canceled",
    doctor: "Dr. David Garcia",
    color: "red",
  },
  {
    date: "2024-06-22",
    user: "Diego Vega",
    time: "9:00 AM",
    duration: "45 minutos",
    reason: "Consulta por diabetes",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-06-27",
    user: "Carmen Silva",
    time: "11:30 AM",
    duration: "1 hora",
    reason: "Revisión de tratamiento",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-07-01",
    user: "Luis Sanchez",
    time: "2:30 PM",
    duration: "30 minutos",
    reason: "Consulta de control",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
  {
    date: "2024-07-05",
    user: "Veronica Castro",
    time: "10:00 AM",
    duration: "45 minutos",
    reason: "Consulta por migrañas",
    state: "canceled",
    doctor: "Dr. David Garcia",
    color: "red",
  },
  {
    date: "2024-07-10",
    user: "Andres Marin",
    time: "1:45 PM",
    duration: "1 hora",
    reason: "Consulta de rutina",
    state: "pending",
    doctor: "Dr. Doctor Prueba",
    color: "orange",
  },
  {
    date: "2024-07-12",
    user: "Angela Morales",
    time: "3:30 PM",
    duration: "30 minutos",
    reason: "Consulta por insomnio",
    state: "confirmed",
    doctor: "Dr. David Garcia",
    color: "green",
  },
  {
    date: "2024-07-18",
    user: "Samuel Paredes",
    time: "9:15 AM",
    duration: "45 minutos",
    reason: "Revisión de exámenes",
    state: "canceled",
    doctor: "Dr. Doctor Prueba",
    color: "red",
  },
  {
    date: "2024-07-20",
    user: "Monica Reyes",
    time: "11:45 AM",
    duration: "1 hora",
    reason: "Consulta por ansiedad",
    state: "pending",
    doctor: "Dr. David Garcia",
    color: "orange",
  },
  {
    date: "2024-07-25",
    user: "Raul Salazar",
    time: "2:00 PM",
    duration: "30 minutos",
    reason: "Consulta de seguimiento",
    state: "confirmed",
    doctor: "Dr. Doctor Prueba",
    color: "green",
  },
];
